spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: validate